<h2>New Products David</h2>
<ul>
    <li><span><?php echo $this->__('David');?></span></li>
    <li><span><?php echo $this->__('David');?></span></li>
    <li><a><?php echo $this->__('David');?></a></li>
</ul>
<?php $products = $this->getProducts(); ?>
<?php echo $this->printMessage("Productos!!!");?>
<ul>
    <?php foreach($products as $product):?>
        <li><?php echo $product->getName();?></li>
    <?php endforeach;?>
</ul>